package: for_sa11y
version: '4.4.42'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/addon_key
perm: for_sa11y[]
requires:
    redaxo: '^5.16.0'
    php:
        version: '>=8.1, <9'
page:
    title: translate:for_sa11y_title
    icon: rex-icon fa-solid fa-universal-access
    perm: for_sa11y[settings]
    subpages:
        config: { title: 'translate:for_sa11y_config' }
        help:  
             { title: 'translate:for_sa11y_help',  icon: rex-icon fa-question-circle, subPath: README.md} 
default_config:
    root: 'body'
    active: 'true'
    ignore: '.rex-minibar,.consent_manager-wrapper,.sa11y-ignore'
    panel_position: 'bottom-right'
    delay_check: 0
    contrast_plugin: 0
    form_labels_plugin: 0
    readability_plugin: 0
    readability_root: 'body'
    export_results_plugin: 1
    show_good_image_button: 1
    show_good_link_button: 1
    detect_spa_routing: 0
    links_to_flag: ''
    about_content: ''
